<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\img\" />
    <Folder Include="wwwroot\fonts\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" />
    <PackageReference Include="Rebus.AzureQueues" />
    <PackageReference Include="Rebus.ServiceProvider" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GloboTicket.Messages\GloboTicket.Messages.csproj" />
  </ItemGroup>

</Project>
