<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <UserSecretsId>dotnet-GloboTicket.Services.Payment-FE161654-5659-4A84-B25C-238F08B1E8E1</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="WolverineFx" />
    <PackageReference Include="WolverineFx.RabbitMQ" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GloboTicket.Messages\GloboTicket.Messages.csproj" />
    <ProjectReference Include="..\GloboTicket.ServiceDefaults\GloboTicket.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
